
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: mosquitto
  ports:
    - name: mqtts
      protocol: TCP
      port: 8883
      targetPort: 8883
