apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: default
  labels:
    app: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
