apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: default
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6.10
        imagePullPolicy: Always
        ports:
        - containerPort: 8883
          name: "mqtts"
          protocol: TCP
        volumeMounts:
          - name: tls-ca
            mountPath: /mosquitto/tls-ca
            readOnly: true
          - name: tls-server
            mountPath: /mosquitto/tls-server
            readOnly: true
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          - name: mosquitto-data
            mountPath: /mosquitto/data
            subPath: mosquitto/data
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: tls-ca
          secret:
            secretName: mqtt-ca
        - name: tls-server
          secret:
            secretName: mqtt-tls
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto
            emptyDir:
