apiVersion: apps/v1
kind: Deployment
metadata:
  name: beq-1
  namespace: sensors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beq-1
  template:
    metadata:
      labels:
        app: beq-1
    spec:
      containers:
      - name: beq-1
        image: nkv21/beq-controller
        imagePullPolicy: Always
