apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-certs
  labels:
    app: mosquitto
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDRjCCAi4CCQDoZrRXa8eiTjANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJO
    TzEOMAwGA1UECAwFT3Nsb1YxDTALBgNVBAcMBE9zbG8xEjAQBgNVBAoMCW5pY292
    YXRuZTELMAkGA1UECwwCQ0ExFjAUBgNVBAMMDW5pY292YXRuZS5jb20wHhcNMjIw
    MzEwMjMzNzE0WhcNMjMwMzEwMjMzNzE0WjBlMQswCQYDVQQGEwJOTzEOMAwGA1UE
    CAwFT3Nsb1YxDTALBgNVBAcMBE9zbG8xEjAQBgNVBAoMCW5pY292YXRuZTELMAkG
    A1UECwwCQ0ExFjAUBgNVBAMMDW5pY292YXRuZS5jb20wggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDE0aOczPe8Jk+PpRs0kGHOfa6w/tXGyvpNMK4yL9xL
    f+PKfAABfGDqdm3dmszk0jOggWwriSiLP05ywv/fdZd5fYMGFZ/9bO8fwZsOJuGj
    7zT55tD08lpDkKda7Ik4apulEOJHHWoEMImbW/x9AJmwWcG7DgYXzM/9Bi4foCLT
    WJLyFzspWeMm4zqoIUKDNhmJS+f0SO/qeqhnC33FgoYZkveZ6LVmue1RTv4sgOcf
    MMgQT1ltOkYMCvWFw6b9heFwK6M9t/DDCFQkagUIhxXOJN7QEFmYzM7GJGtj9IGT
    CphTp3ZlZoquRD+WObKQ6qlriskNFvdTQDXwWWDYETpzAgMBAAEwDQYJKoZIhvcN
    AQELBQADggEBAC/6v09PfsTcyWdp0QrflqpvD7lfZp5tKj6qFnbiXcb3Ezog/ScZ
    Roh1g2vnv/usyeeIOaNKgqsIQFsK+A3MoQ9ePHf4VqxZue+VxWjb3SXGGzuoPB5X
    BnpLZcLUhGKfyXXCeqqI/jdyo6/Mh8cA3Qwei7M1zE0CELYJTzuT3+sXdhnUb7l8
    06UFCQ9Otff2aoFYb6TyaNZ+4py5dz8K8jh673Uw+99uP38a/BAItBtX1RcSd1wi
    LIknYLGQ6lzBveYQakE7fQKq1h3YwStKWkRmulLQqBlXh8K9bkn1gK1E6194f+zw
    kLgcX+D0zKX25uSQsOu7Tx8X/KvnlwPEOy8=
    -----END CERTIFICATE-----
  server.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDSjCCAjICCQDzq6+ln8MxXjANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJO
    TzEOMAwGA1UECAwFT3Nsb1YxDTALBgNVBAcMBE9zbG8xEjAQBgNVBAoMCW5pY292
    YXRuZTELMAkGA1UECwwCQ0ExFjAUBgNVBAMMDW5pY292YXRuZS5jb20wHhcNMjIw
    MzEwMjMzNzE0WhcNMjMwMzEwMjMzNzE0WjBpMQswCQYDVQQGEwJOTzEOMAwGA1UE
    CAwFT3Nsb08xDTALBgNVBAcMBE9zbG8xEjAQBgNVBAoMCW5pY292YXRuZTEPMA0G
    A1UECwwGU2VydmVyMRYwFAYDVQQDDA1uaWNvdmF0bmUuY29tMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4ame6opkGOuylHf+lfxrTmsb2TV7NW/spPIZ
    oBCLJHeMDxvZoet9P87/USt1tzQ+m9zfCgbfA6SXyE/yGp0siVjvkOsOsh9z9HSb
    ugz6vTmlwxdJ/R8ySNX7rex8Q3KUL+0qlj1Uh9lHW0yUmynGMAE+OVlNHxZtb3+L
    +w4yD+fADd+JMnft8vWbx59oAdTT95AzA37HR5XijPKBBWMJmXuQ6sXxiQzFd1T8
    CnLJCyBTtokKRWFrCobSRTvst/0wNVPneP0s3Yvsu1DSf7X+m3uPSvXbcY+JQEye
    3qAcBy3gQbtaV2iV4JBbYq3MmpPMXXY4I5P4zML0kxxcX9llNQIDAQABMA0GCSqG
    SIb3DQEBCwUAA4IBAQARM7Pj7nyQvyewULyYJ9f1y/nRY1C6hzHf8CJu6396f6OE
    bCUtU3GBS+0T3d1iHG5wRcauir7/1LH4ZDOGPF+mwqBA4KnNRFOMs0asmOvbWA69
    n1BAtzXfEpKi9xaMd1Jq/8H+Yjjdt+hga5Nf8AhzSS+O0mNri1j3LCTpoqN01Lip
    9TNYzBPNrPwT+hugvcw/85N80kf4ZskuvrLdIF7B/U4/LBXybsaSe6LiTHbct3T3
    xQL1LqUOG0cjeCt8Xg04hXfFMpA+SsG7zaGj4z1YkB0vSNWbTZz51Okujy1rkQoD
    zXTjWgHAn+gADWa35WJqzOixWK1v0G4mXwRGKYV0
    -----END CERTIFICATE-----
  server.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhqZ7qimQY67KU
    d/6V/GtOaxvZNXs1b+yk8hmgEIskd4wPG9mh630/zv9RK3W3ND6b3N8KBt8DpJfI
    T/IanSyJWO+Q6w6yH3P0dJu6DPq9OaXDF0n9HzJI1fut7HxDcpQv7SqWPVSH2Udb
    TJSbKcYwAT45WU0fFm1vf4v7DjIP58AN34kyd+3y9ZvHn2gB1NP3kDMDfsdHleKM
    8oEFYwmZe5DqxfGJDMV3VPwKcskLIFO2iQpFYWsKhtJFO+y3/TA1U+d4/Szdi+y7
    UNJ/tf6be49K9dtxj4lATJ7eoBwHLeBBu1pXaJXgkFtircyak8xddjgjk/jMwvST
    HFxf2WU1AgMBAAECggEAPJ9ax9thxKgdE3Gg/R4QncJ8er+5V8O3qSA47h1DpApR
    oAV1U+B1h1zOjjnEp/DrGOgfKwxpgQsIk5GWkrvCqSsxQJdFHWkBt5xT8YlnGsqP
    03dAMzXcRmDl+fVb9KqlULLADBhxywT9/HL4QS7ZxS+wTavF4iIeSCPVsR5BKLAy
    axIMgygBKvsLtQ9XewiqlerfMcRo4Gfhm+BOhW8wxJLyU8/UEKfwDRlDGnqHlB5q
    X4FSljlCqdbOuZIxzXfJuGt26zJp1Hw6Nde0KKarCbs841A9yoTdamCxcomEAICh
    H5YjgxIxXiJ4s/gBVXUOWVdWGtDU/JXnIpWSXbaYyQKBgQDzsDpPpTc6C99U5hyM
    l20lS7snTj8Kg4b6jwSwo6yZYW5Lu2lUvqtka4iVnpQQbv/JBuliyTHm7EPexg5/
    zaxnAnqUi20gEwzrrope+n9gltcFQ0P2VpqzXD4TR5ng/S+0qWTn2MCTcPHBvoCQ
    vTVB2wU7ylMWMHFQOtKmfmxPYwKBgQDtEEEL/k/oStTsAFJfB+BfvKYfNkl/zNvW
    +6lwVLe3CNuHVU9pVtdwCWx87w9JGpm3EJWIYAIjB6TqtXVSoYgjjN3P4SAwhLrf
    K2YTqgwEo5/gkSxlqUxeyT4YYdmrstPzO6NhLIktYkYQwCvgjucyChRmYDCwoPzu
    31Rtc0DYhwKBgHmyg5xs3QS/ExxaAt3vbZGXnXKGsBL3Fnyg2e3A/5xlvOhTQsoQ
    opV24nIeDMGcPV9OdVVhNuulCEwDyw/mTffvk/oFG01OVkCJHQ9LuDsreVxmeFVY
    cM+r/FAyjNWAe8eUZREn/Rxk5kckdR5Tb3pg/98ZLp9BOAWiKrr9HegTAoGBAJ2n
    cZrIRdv16CQLErygQFdq3g9jyv1y/8C5HLXXoVXYTiZyVZ14Y03e9ocfdMrpJdDY
    9pj7QHCLZOGyS5PoWOFLjTfyP7YEj0JbWkc5j0SGjIyL/zqcnG1s6B7O9DN7efkI
    cF7vf0rvUClTo9pzLs3YZjivP7I3Xf5+B2fCfh2BAoGAYVbVqoVOmULYXbVpALl7
    QNqgq857m/NLQrkTVQjKUj6e20iyNEjsIf+8j9LhpZMNlwta6md4ezs7OoWbPTfe
    OY8cycm13oLVFSc4RtTkoLOsyq7iuFr5F+Pd0/MLrriDhIjcUT6eTTdzPZ3Ghsww
    ImazAyAcC0dzAAtR22mJwQA=
    -----END PRIVATE KEY-----
