apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: default
data:
  mosquitto.conf : |-
    log_dest stdout
    listener 8883
    allow_anonymous false
    cafile /mosquitto/config/certs/ca.crt
    certfile /mosquitto/config/certs/server.crt
    keyfile /mosquitto/config/certs/server.key
