apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: default
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6.10
        imagePullPolicy: Always
        ports:
        - containerPort: 8883
          hostPort: 8883
          name: "mqtts"
          protocol: TCP
        volumeMounts:
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          - name: mosquitto-ca-certs
            mountPath: /mosquitto/config/certs/ca.crt
            subPath: ca.crt
            readOnly: true
          - name: mosquitto-server-certs
            mountPath: /mosquitto/config/certs/server.crt
            subPath: server.crt
            readOnly: true
          - name: mosquitto-server-key
            mountPath: /mosquitto/config/certs/server.key
            subPath: server.key
            readOnly: true


      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-ca-certs
          configMap:
            name: mosquitto-certs
            items:
               - key: ca.crt
                 path: ca.crt
        - name: mosquitto-server-certs
          configMap:
            name: mosquitto-certs
            items:
               - key: server.crt
                 path: server.crt
        - name: mosquitto-server-key
          configMap:
            name: mosquitto-certs
            items:
               - key: server.key
                 path: server.key
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto
            emptyDir:
