apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: mosquitto-verified
  labels:
    app: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
