apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  namespace: mosquitto-verified
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6.10
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
          name: "mqqt-secure"
        - containerPort: 1883
          name: "mqqt-basic"
        volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          - name: mosquitto-ca-cert
            mountPath: /mosquitto/config/certs/ca.crt
            subPath: ca.crt
          - name: mosquitto-server-cert
            mountPath: /mosquitto/config/certs/server.crt
            subPath: server.crt
          - name: mosquitto-server-key
            mountPath: /mosquitto/config/certs/server.key
            subPath: server.key
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf
        - name: mosquitto-ca-cert
          configMap:
            name: mosquitto-certs
            items:
              - key: ca.crt
                path: ca.crt
        - name: mosquitto-server-cert
          configMap:
            name: mosquitto-certs
            items:
              - key: server.crt
                path: server.crt
        - name: mosquitto-server-key
          configMap:
            name: mosquitto-certs
            items:
              - key: server.key
                path: server.key
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto
            emptyDir:
